name: Build, Deploy, and Test

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      REPO_DIR: 'DevOps-exam'
      DOCKER_IMAGE: 'ttl.sh/alukan-devops:latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_IMAGE }}

  test:
    runs-on: self-hosted
    needs: build-and-push

    env:
      CONTAINER_NAME: 'alukan-devops-test'
      DOCKER_IMAGE: 'ttl.sh/alukan-devops:latest'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Start Docker container for testing
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.105.3
          username: vagrant
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl start docker
            sudo docker ps -a
            sudo docker stop ${{ env.CONTAINER_NAME }} || true
            sudo docker rm ${{ env.CONTAINER_NAME }} || true
            sudo docker run -d --name ${{ env.CONTAINER_NAME }} ${{ env.DOCKER_IMAGE }} sleep infinity

      - name: Run tests in Docker container
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.105.3
          username: vagrant
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker exec ${{ env.CONTAINER_NAME }} env NODE_ENV=test node --test

      - name: Stop and remove test container
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.105.3
          username: vagrant
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop ${{ env.CONTAINER_NAME }}
            sudo docker rm ${{ env.CONTAINER_NAME }}

  staging:
    runs-on: self-hosted
    needs: test

    env:
      CONTAINER_NAME: 'alukan-devops'
      CONTAINER_PORT: '4444'
      DOCKER_IMAGE: 'ttl.sh/alukan-devops:latest'

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.105.3
          username: vagrant
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl start docker
            sudo docker ps -a
            sudo docker stop ${{ env.CONTAINER_NAME }} || true
            sudo docker rm ${{ env.CONTAINER_NAME }} || true
            sudo docker pull ${{ env.DOCKER_IMAGE }}
            sudo docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.CONTAINER_PORT }}:${{ env.CONTAINER_PORT }} ${{ env.DOCKER_IMAGE }} node index.js

